services:
  postgres:
    image: postgres:15.0
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crm_db
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  spring-crm:
    image: spring-crm:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres:5432
      POSTGRES_DB_NAME: crm_db
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin

    depends_on:
      - postgres
volumes:
  postgres_data: