create table public.user_account
(
    id          bigint generated by default as identity primary key,
    username    varchar(255),
    password    varchar(60),
    first_name  varchar(255),
    last_name   varchar(255),
    email       varchar(255),
    is_using2fa boolean not null,
    enabled     boolean not null
);
alter table public.user_account owner to admin;

create table public.role
(
    id   bigint not null primary key,
    name varchar(255)
);
alter table public.role owner to admin;

create table public.privilege
(
    id   bigint not null primary key,
    name varchar(255)
);
alter table public.privilege owner to admin;

create table public.users_roles
(
    user_id bigint not null constraint fkci4mdvg1fmo9eqmwno1y9o0fa references public.user_account,
    role_id bigint not null constraint fkt4v0rrweyk393bdgt107vdx0x references public.role
);
alter table public.users_roles owner to admin;

create table public.roles_privileges
(
    role_id      bigint not null constraint fk9h2vewsqh8luhfq71xokh4who references public.role,
    privilege_id bigint not null constraint fk5yjwxw2gvfyu76j3rgqwo685u references public.privilege
);
alter table public.roles_privileges owner to admin;